"""Pydantic schemas for API validation."""

from app.schemas.user import (
    GitIdentityCreate,
    GitIdentityResponse,
    UserCreate,
    UserUpdate,
    UserResponse,
    UserListResponse,
    MagicLinkRequest,
    MagicLinkResponse,
    TokenVerifyRequest,
    TokenResponse,
    CurrentUser,
)
from app.schemas.project import (
    ProjectCreate,
    ProjectUpdate,
    ProjectResponse,
    ProjectWithRepos,
    RepositoryCreate,
    RepositoryUpdate,
    RepositoryResponse,
    RepositorySyncRequest,
    RepositorySyncResponse,
    RepositoryTestConnectionRequest,
    RepositoryTestConnectionResponse,
)
from app.schemas.commit import (
    CommitResponse,
    CommitListResponse,
    CommitStatsResponse,
)
from app.schemas.scoring import (
    ScoringCoefficientsSchema,
    ProjectConfigResponse,
    ProjectConfigUpdate,
    CommitMetricsResponse,
    CommitMetricsBreakdown,
)

__all__ = [
    "GitIdentityCreate",
    "GitIdentityResponse",
    "UserCreate",
    "UserUpdate",
    "UserResponse",
    "UserListResponse",
    "MagicLinkRequest",
    "MagicLinkResponse",
    "TokenVerifyRequest",
    "TokenResponse",
    "CurrentUser",
    "ProjectCreate",
    "ProjectUpdate",
    "ProjectResponse",
    "ProjectWithRepos",
    "RepositoryCreate",
    "RepositoryUpdate",
    "RepositoryResponse",
    "RepositorySyncRequest",
    "RepositorySyncResponse",
    "RepositoryTestConnectionRequest",
    "RepositoryTestConnectionResponse",
    "CommitResponse",
    "CommitListResponse",
    "CommitStatsResponse",
    "ScoringCoefficientsSchema",
    "ProjectConfigResponse",
    "ProjectConfigUpdate",
    "CommitMetricsResponse",
    "CommitMetricsBreakdown",
]
