"""Pydantic schemas for API validation."""

from app.schemas.user import (
    GitIdentityCreate,
    GitIdentityResponse,
    UserCreate,
    UserUpdate,
    UserResponse,
    UserListResponse,
    MagicLinkRequest,
    MagicLinkResponse,
    TokenVerifyRequest,
    TokenResponse,
    CurrentUser,
)
from app.schemas.project import (
    ProjectCreate,
    ProjectUpdate,
    ProjectResponse,
    ProjectWithRepos,
    RepositoryCreate,
    RepositoryUpdate,
    RepositoryResponse,
    RepositorySyncRequest,
    RepositorySyncResponse,
    RepositoryTestConnectionRequest,
    RepositoryTestConnectionResponse,
)
from app.schemas.commit import (
    CommitResponse,
    CommitListResponse,
    CommitStatsResponse,
)
from app.schemas.scoring import (
    ScoringCoefficientsSchema,
    ProjectConfigResponse,
    ProjectConfigUpdate,
    CommitMetricsResponse,
    CommitMetricsBreakdown,
)
from app.schemas.season import (
    SeasonCreate,
    SeasonUpdate,
    SeasonResponse,
    SeasonActivateRequest,
    AbsenceCreate,
    AbsenceUpdate,
    AbsenceResponse,
)
from app.schemas.leaderboard import (
    PlayerPeriodStatsBase,
    PlayerPeriodStatsResponse,
    PlayerInfo,
    LeaderboardEntry,
    LeaderboardResponse,
)
from app.schemas.player import (
    PlayerSeasonStats,
    PlayerCareerStats,
    RepoContribution,
    PlayerCommitSummary,
    PlayerProfileResponse,
    TrendDataPoint,
    PlayerTrendResponse,
)

__all__ = [
    "GitIdentityCreate",
    "GitIdentityResponse",
    "UserCreate",
    "UserUpdate",
    "UserResponse",
    "UserListResponse",
    "MagicLinkRequest",
    "MagicLinkResponse",
    "TokenVerifyRequest",
    "TokenResponse",
    "CurrentUser",
    "ProjectCreate",
    "ProjectUpdate",
    "ProjectResponse",
    "ProjectWithRepos",
    "RepositoryCreate",
    "RepositoryUpdate",
    "RepositoryResponse",
    "RepositorySyncRequest",
    "RepositorySyncResponse",
    "RepositoryTestConnectionRequest",
    "RepositoryTestConnectionResponse",
    "CommitResponse",
    "CommitListResponse",
    "CommitStatsResponse",
    "ScoringCoefficientsSchema",
    "ProjectConfigResponse",
    "ProjectConfigUpdate",
    "CommitMetricsResponse",
    "CommitMetricsBreakdown",
    "SeasonCreate",
    "SeasonUpdate",
    "SeasonResponse",
    "SeasonActivateRequest",
    "AbsenceCreate",
    "AbsenceUpdate",
    "AbsenceResponse",
    "PlayerPeriodStatsBase",
    "PlayerPeriodStatsResponse",
    "PlayerInfo",
    "LeaderboardEntry",
    "LeaderboardResponse",
    "PlayerSeasonStats",
    "PlayerCareerStats",
    "RepoContribution",
    "PlayerCommitSummary",
    "PlayerProfileResponse",
    "TrendDataPoint",
    "PlayerTrendResponse",
]
